import {useState} from 'react';
import schemes from '../data/gaurav-schemes-data.json';
import {useLanguage,LanguageSwitch} from '../locale/context.js';
export const schemeSlug = scheme => scheme.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export function findScheme(id){if(id===undefined)return null;return /^\d+$/.test(String(id))?schemes[Number(id)]:schemes.find(s=>schemeSlug(s)===id);}
const labels={need:'The public need',vision:'Vision',policy:'Policy design',work:'Implementation',responsibility:'Responsible institutions',beneficiaries:'Intended beneficiaries',evidence:'Reported benefits',district_application:'District connection',challenges:'Challenges'};
export default function DevelopmentPage({id}){const [theme,setTheme]=useState('All');const {language,setLanguage}=useLanguage();const s=findScheme(id);
 if(id!==undefined&&!s)return <main id="page-content" className="route-page"><h1 tabIndex={-1}>Initiative not found</h1><a href="/development">All initiatives</a></main>;
 return <main className="route-page" id="page-content" lang={language==='gu'?'gu':'en'}><nav className="breadcrumbs"><a href="/">Gujarat</a><span>/</span><a href="/development">Development</a></nav><LanguageSwitch/><span className="eyebrow">{language==='gu'?'જાહેર સેવાઓ અને સ્થિતિસ્થાપકતા':'PUBLIC SERVICES & RESILIENCE'}</span><h1 tabIndex={-1}>{s?s.name:(language==='gu'?'વિચારો, સંસ્થાઓ અને જાહેર મૂલ્ય.':'Ideas, institutions and public value.')}</h1>{s?<div className="reading-layout"><aside className="chapter-nav">{Object.keys(labels).filter(k=>s[k]).map(k=><a key={k} href={'#'+k}>{labels[k]}</a>)}</aside><article className="reading-body">{Object.entries(labels).filter(([k])=>s[k]).map(([k,title])=><section id={k} key={k}><h2>{title}</h2><p>{s[k]}</p></section>)}<section><h2>Evidence status</h2><p className="evidence-note">This is an overview from the supplied project, not a verified current performance report. Reporting dates, expenditure and district-level outcome evidence are not yet supplied for this entry.</p>{s.sources?.map(x=><p key={x.url}><a href={x.url}>{x.title} ↗</a></p>)}</section></article></div>:<><p className="page-intro">{language==='gu'?'યોજનાઓ કેવી રીતે કામ કરે છે, કઈ સંસ્થાઓ જોડાયેલી છે અને નીતિનું લક્ષ્ય તથા માપેલા પરિણામ વચ્ચેનો ભેદ સમજો.':'Explore how initiatives are intended to work, the institutions involved and the distinction between a policy objective and a measured result.'}</p><div className="directory-controls"><label>Theme<select value={theme} onChange={e=>setTheme(e.target.value)}><option>All</option>{[...new Set(schemes.map(s=>s.theme))].map(t=><option key={t}>{t}</option>)}</select></label></div><div className="district-route-grid">{schemes.map((s,i)=>({...s,index:i})).filter(s=>theme==='All'||s.theme===theme).map(s=><a key={s.index} href={'/development/'+schemeSlug(s)} className="related-card"><span className="eyebrow">{s.theme}</span><h2>{s.name}</h2><p>{s.need}</p><strong>Explore the initiative ↗</strong></a>)}</div></>}</main>}
