import {useState,useEffect} from 'react';
import {districtBySlug,localStories} from '../data/districts.js';
import contributions from '../data/gaurav-districts-data.json';
import texts from '../data/district-texts.json';
import recordings from '../data/district-recordings.json';
import {episodes} from '../data/content.js';
export default function DistrictPage({slug}){
 const [query,setQuery]=useState('');const d=districtBySlug[slug],profile=contributions.find(p=>p.id===slug);const sections=(texts[slug]||'').split(/\n\s*\n/).filter(Boolean);
 if(!slug)return <main className="route-page" id="page-content"><span className="eyebrow">DISTRICT ATLAS</span><h1 tabIndex={-1}>34 districts.<br/><em>Many ways to understand Gujarat.</em></h1><div className="directory-controls"><label>Find a district<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="English or ગુજરાતી"/></label></div><div className="district-route-grid">{Object.entries(districtBySlug).filter(([s,d])=>(d.name+d.gu).toLowerCase().includes(query.toLowerCase())).map(([s,d])=><a className="related-card" key={s} href={'/districts/'+s}><span className="eyebrow">{d.region} Gujarat</span><h2 lang="gu">{d.gu}</h2><strong>{d.name}</strong><p>{d.teaser}</p></a>)}</div></main>;
 if(!d)return <main className="route-page"><h1>District not found</h1><a href="/districts">All districts</a></main>;
 return <main className="route-page" id="page-content"><nav className="breadcrumbs"><a href="/districts">All districts</a><span>/</span><span>{d.name}</span></nav><header className="directory-heading"><span className="eyebrow">{d.region} GUJARAT</span><h1 tabIndex={-1} lang="gu">{d.gu}</h1><p>{d.teaser}</p></header><div className="tag-list"><a href="#district-story">ગુજરાતી વાર્તા</a><a href="#district-context">District context</a><a href="#local-stories">Related subjects</a><button onClick={()=>window.print()}>Print reading view</button></div><div className="reading-layout"><aside className="chapter-nav"><h2>Explore this district</h2><a href="#district-story">Read in Gujarati</a>{profile&&Object.keys(profile).filter(k=>k!=='id'&&typeof profile[k]==='string').map(k=><a key={k} href={'#district-'+k}>{k.replace(/_/g,' ')}</a>)}<a href={d.site} target="_blank" rel="noopener noreferrer">District administration ↗</a></aside><article className="reading-body"><section id="district-story"><h2 lang="gu">જિલ્લાની સફર</h2>{recordings[slug]?<button data-recording={slug} className="primary">Play district narration</button>:<p className="evidence-note" lang="gu">જિલ્લાની અલગ રેકોર્ડિંગ ઉપલબ્ધ થયા પછી અહીં સાંભળી શકશો. હાલ સંપૂર્ણ લખાણ વાંચો.</p>}{sections.map((p,i)=><p key={i} lang="gu" className="gujarati-text">{p.replace(/\*\*/g,'')}</p>)}</section><section id="district-context"><h2>District context</h2></section>{profile&&Object.entries(profile).filter(([k,v])=>k!=='id'&&typeof v==='string').map(([k,v])=><section id={'district-'+k} key={k}><h2>{k.replace(/_/g,' ')}</h2><p>{v}</p></section>)}<section id="local-stories"><h2>Explore a subject</h2><div className="tag-list">{(localStories[d.id]||[]).map(id=><button key={id} data-info={id}>{episodes[id].title}</button>)}</div></section><section><h2>Sources and context</h2><a href={d.site} target="_blank" rel="noopener noreferrer">Official district information ↗</a><p className="evidence-note">District boundaries and data periods can differ between historical sources. The original supplied narrative is retained; a complete claim-by-claim editorial review remains necessary.</p></section></article></div></main>
}
