import {useState} from 'react';
import {atlasData,connectionsData,objectsData,peopleData,ecologyStories,historicalImage} from '../data/explorer-expansion.js';
import envData from '../data/environment.json';
import {explorerNames,explorerPath,parseExplorerRoute,seasonalObservations,relatedRecords} from './explorer-model.js';
import explorerMedia from '../data/explorer-media.json';
import {LanguageSwitch,useLanguage,translateText} from '../locale/context.js';
import '../explorers.css';
const collections={history:atlasData.sites,connections:connectionsData,objects:objectsData,people:peopleData,environment:ecologyStories};
const fieldLabels={evidence:'Archaeological evidence',location_note:'Location and historical geography',development:'What developed here',local_conditions:'Why this location',contributors:'People and institutions',evolution:'How it changed',connections:'Wider connections',modern_relevance:'Why it matters today',origin_date:'Period and origin',present_location:'Present location',materials_technique:'Materials and technique',makers_users:'Makers and users',meaning:'Meaning and cultural context',linked_places:'Connected places',revelation:'What this object reveals',rainfall_temp:'Climate pattern',water_wetlands:'Water and wetlands',agriculture_livelihoods:'Agriculture and livelihoods',wildlife_activity:'Wildlife'};
function Sources({items=[]}){const sources=Array.isArray(items)?items:[items];return <section className="explorer-sources"><h2>References</h2><ul>{sources.map((s,i)=><li key={i}>{/^https?:/.test(s)?<a href={s} target="_blank" rel="noreferrer">{new URL(s).hostname} ↗</a>:s}</li>)}</ul></section>}
function Fields({record}){return <div className="reading-body">{Object.entries(fieldLabels).filter(([key])=>record[key]).map(([key,label])=><section id={key} key={key}><h2>{label}</h2><p>{record[key]}</p></section>)}</div>}
function StoryImage({record,kind}){const media=explorerMedia[record.id];const src=media?.src||record.image||(kind==='history'?historicalImage(record):null);const caption=media?.original?.includes('IVC_Map')?'Map of Indus civilisation sites · regional context':media?.title||record.imageCaption||record.name||record.title;return src?<figure className="story-figure"><img className="explorer-story-image" src={src} alt={caption} loading="lazy"/><figcaption>{caption}</figcaption></figure>:null}
function Cards({kind,records}){return <div className="explorer-grid">{records.map(record=><article className="explorer-card" key={record.id}><a className="explorer-image-link" href={explorerPath(kind,record.id)}><StoryImage record={record} kind={kind}/></a><span className="explorer-kicker">{record.type||record.category||record.dates}</span><h2><a href={explorerPath(kind,record.id)}>{record.name||record.title}</a></h2><p>{record.recognition||record.overview||record.description||record.development}</p><a className="explorer-read" href={explorerPath(kind,record.id)}>Read the full story ↗</a></article>)}</div>}
function Detail({kind,record}){const related=relatedRecords(kind,record.id,collections);return <><span className="eyebrow">{record.type||record.category||record.dates}</span><h1 tabIndex={-1}>{record.name||record.title}</h1><p className="page-intro">{record.description||record.overview||record.recognition}</p><StoryImage record={record} kind={kind}/><div className="reading-layout"><aside className="chapter-nav"><h2>In this story</h2>{Object.entries(fieldLabels).filter(([key])=>record[key]).map(([key,label])=><a key={key} href={'#'+key}>{label}</a>)}{record.script_chapters?.map((c,i)=><a key={i} href={'#chapter-'+i}>{c.title}</a>)}</aside><article><Fields record={record}/>{record.sections?.map((s,i)=><section className="explorer-chapter" key={i}><h2>{s.title}</h2><p>{s.text}</p></section>)}{record.script_chapters?.map((chapter,i)=><section className="explorer-chapter" id={'chapter-'+i} key={i}><h2>{chapter.title}</h2><p className="gujarati-text">{chapter.gujarati_script}</p></section>)}{record.legacy&&<section className="explorer-chapter"><h2>Legacy</h2><p>{record.legacy}</p><a href="/leadership">Explore leadership and personalities ↗</a></section>}<Sources items={record.sources}/></article></div>{related.length>0&&<section className="explorer-related"><h2>Follow this connection</h2>{related.map(({kind,record})=><p key={record.id}><a href={explorerPath(kind,record.id)}>{record.name||record.title} ↗</a></p>)}</section>}</>}
function Directory({kind}){const {language}=useLanguage();const [eraId,setEraId]=useState('all');const [query,setQuery]=useState('');const era=atlasData.eras.find(e=>e.id===eraId);const records=collections[kind].filter(r=>(kind!=='history'||eraId==='all'||r.era_id===eraId)&&[r.name||r.title,r.description||r.overview||'',translateText(r.name||r.title,language)].join(' ').toLowerCase().includes(query.toLowerCase()));return <><h1 tabIndex={-1}>{explorerNames[kind]}</h1><p className="page-intro">Read the evidence, understand the setting, and follow the connections between places, people and ideas.</p><div className="directory-controls"><label>Find a story<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stories"/></label></div>{kind==='history'&&<><nav className="explorer-filters"><button onClick={()=>setEraId('all')} aria-pressed={eraId==='all'}>All periods</button>{atlasData.eras.map(e=><button key={e.id} onClick={()=>setEraId(e.id)} aria-pressed={eraId===e.id}>{e.name}</button>)}</nav>{era&&<section className="explorer-era"><h2>{era.name}</h2><p>{era.date_range}</p><p>{era.description}</p></section>}</>}<p role="status">{records.length} <span>stories available</span></p><Cards kind={kind} records={records}/></>}
function Environment({regionId,search}){const story=ecologyStories.find(s=>s.id===regionId);if(story)return <Detail kind="environment" record={story}/>;const requested=new URLSearchParams(search).get('season');const season=envData.seasons.find(s=>s.id===requested)||envData.seasons[0];const region=envData.regions.find(r=>r.id===regionId);if(regionId&&!region)return <NotFound/>;const records=seasonalObservations(envData,season.id,regionId||'all');return <><h1 tabIndex={-1}>Seasonal Gujarat</h1><p className="page-intro">Water, habitats and livelihoods change together through the year. Compare seasonal observations, then read the ecological stories below.</p><nav className="explorer-filters">{envData.seasons.map(s=><a key={s.id} aria-current={s.id===season.id?'page':undefined} href={explorerPath('environment',regionId)+'?season='+s.id}>{s.name}</a>)}</nav><nav className="explorer-filters"><a href={'/explore/environment?season='+season.id}>All regions</a>{envData.regions.map(r=><a key={r.id} href={explorerPath('environment',r.id)+'?season='+season.id}>{r.name}</a>)}</nav><div className="explorer-grid">{records.map(r=><article className="explorer-card" key={r.id}><h2>{envData.regions.find(x=>x.id===r.region_id)?.name}</h2><Fields record={r}/></article>)}</div><h2>Read the living landscape</h2><Cards kind="environment" records={ecologyStories}/></>}
function NotFound(){return <><h1>Explorer page not found</h1><a href="/explore-deeper">Browse available subjects →</a></>}
export default function Explorers({route,search=''}){const parsed=parseExplorerRoute(route);const record=parsed?.id&&collections[parsed.kind]?.find(r=>r.id===parsed.id);return <main id="page-content" className="route-page explorer-page"><LanguageSwitch/><nav className="breadcrumbs"><a href="/explore-deeper">Explore deeper</a>{parsed?.id&&<a href={explorerPath(parsed.kind)}>{explorerNames[parsed.kind]}</a>}</nav>{!parsed?<NotFound/>:parsed.kind==='environment'?<Environment regionId={parsed.id} search={search}/>:parsed.id?record?<Detail kind={parsed.kind} record={record}/>:<NotFound/>:<Directory key={parsed.kind} kind={parsed.kind}/>}</main>}
