import {atlasData,connectionsData,objectsData,peopleData,ecologyStories} from '../data/explorer-expansion.js';
import {LanguageSwitch} from '../locale/context.js';
const themes=[
['history','Historical Atlas','/assets/dholavira.jpg',atlasData.sites.length,'Read Gujarat through settlement, water, power and memory. Compare Harappan urban planning with stepwells, fortified landscapes, living cities and the public movements of the twentieth century.','Begin with a place and ask what survives. Buildings, inscriptions, objects and written accounts answer different questions. Separate archaeological observations from interpretation, and distinguish the date of a structure from later rebuilding or commemoration.'],
['connections','Connections: Why Here?','/assets/districts/anand.jpg',connectionsData.length,'Understand why activities developed in particular places: milk cooperatives in Anand, manufacturing in Morbi, craft networks in Kutch and art education in Vadodara.','Follow the relationship between geography, skill, institutions and markets. A useful explanation connects local conditions with decisions made by people. Natural resources create possibilities, but organisation, technology and public infrastructure influence which possibilities become durable livelihoods.'],
['objects','Story Discovery','/assets/patola.jpg',objectsData.length,'Start with an object: a bead, textile, inscription, spinning wheel or carved screen. Small things can open large questions about work, trade, belief and collective identity.','Read the material and the process together. Ask who made an object, how it was used, where it travelled and how it is interpreted today. A museum label, a maker’s explanation and an excavation report offer complementary perspectives, and sometimes leave important questions unanswered.'],
['people','People and their work','/assets/portraits/vikram-sarabhai.webp',peopleData.length,'Explore lives connected with Gujarat across public service, science, enterprise, education, literature and the arts. Move from a short introduction into chapters and related profiles.','Place a biography in its social setting. Institutions, collaborators and communities help explain how an individual’s contribution acquired influence. Compare ideas with specific actions, and distinguish contemporary evidence from the reputation constructed by later generations.'],
['environment','Environmental Understanding','/assets/marine-narara.jpg',ecologyStories.length,'Explore salt landscapes, forests, coasts, wetlands and grasslands through their seasonal processes and the people who live and work in them.','Connect water, vegetation, livelihoods and conservation. A landscape changes through time and extends beyond an administrative boundary. Read the seasonal observations alongside the longer ecological stories to understand why a single photograph or wildlife sighting cannot describe the whole system.']
];
export default function ExploreDeeperHub(){return <main className="route-page explore-deeper-page" id="page-content"><LanguageSwitch/><span className="eyebrow">EXPLORE DEEPER</span><h1 tabIndex={-1}>Gujarat, understood in layers.</h1><p className="page-intro">Five collections. Many connected questions. Follow a place, a person or an object into a fuller account of Gujarat’s past and present.</p><div className="explorer-grid">{themes.map(([id,title,image,count,intro,approach])=><article className="explorer-card" key={id}><a href={'/explore/'+id} className="explorer-image-link"><img className="explorer-story-image" src={image} alt={title}/></a><span className="eyebrow">{count} <span>stories and profiles</span></span><h2>{title}</h2><p>{intro}</p><h3>How to read this collection</h3><p>{approach}</p><a className="primary" href={'/explore/'+id}>Open the collection ↗</a></article>)}</div></main>}
