import {useState} from 'react';
import people from '../data/personalities-data.json';
import {personPath} from '../routes.js';
const labels={contributions_gujarat:'Gujarat connection',contributions_india:'Contribution to India',contributions_international:'Wider influence',roles:'Roles and responsibilities',vision:'Ideas and vision',lessons:'Legacy and reflection'};
function Portrait({person}){const [failed,setFailed]=useState(false);return person.image&&!person.image.includes('ui-avatars')&&!failed?<img src={'/'+person.image.replace(/^\//,'')} alt={person.name} onError={()=>setFailed(true)} loading="lazy"/>:<div className="portrait-placeholder" aria-label={`Portrait unavailable for ${person.name}`}><span>{person.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><small>Portrait unavailable</small></div>}
export default function PersonalitiesPage({id}){
 const [query,setQuery]=useState('');const [tag,setTag]=useState(()=>typeof location!=='undefined'?new URLSearchParams(location.search).get('tag')||'All':'All');
 const list=[...people].sort((a,b)=>a.id==='narendra-modi'?-1:b.id==='narendra-modi'?1:0);
 const person=list.find(p=>p.id===id);const tags=[...new Set(list.flatMap(p=>p.tags))];
 if(id&&!person)return <section className="route-page"><h1 tabIndex={-1}>Profile not found</h1><a href="/leadership">Browse personalities</a></section>;
 if(person){const related=list.filter(p=>p.id!==id&&p.tags.some(t=>person.tags.includes(t)));return <main id="page-content" className="route-page profile-page">
 <nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Gujarat</a><span>/</span><a href="/leadership">Leadership & personalities</a><span>/</span><span>{person.name}</span></nav>
 <header className="profile-hero"><div className="profile-portrait"><Portrait person={person}/></div><div><span className="eyebrow">PEOPLE WHO SHAPED GUJARAT</span><h1 tabIndex={-1}>{person.name}</h1><p className="profile-meta">Born {person.born} · {person.place}</p><p className="profile-intro">{person.relevance}</p><div className="tag-list">{person.tags.map(t=><a key={t} href={'/leadership?tag='+encodeURIComponent(t)}>{t}</a>)}</div></div></header>
 <div className="reading-layout"><aside className="chapter-nav"><h2>In this profile</h2>{Object.keys(person.details).map(k=><a key={k} href={'#'+k}>{labels[k]||k}</a>)}<a href="#related-people">Related people</a><a href="#profile-sources">Sources</a></aside><article className="reading-body">{Object.entries(person.details).map(([k,text])=><section id={k} key={k}><h2>{labels[k]||k}</h2><p>{text}</p></section>)}<section id="profile-sources"><h2>Sources & context</h2>{person.sources?.length?<ul className="source-list">{person.sources.map((s,i)=><li key={i}><a href={typeof s==='string'?s:s.url} target="_blank" rel="noopener noreferrer">{typeof s==='string'?new URL(s).hostname:s.title} ↗</a></li>)}</ul>:<p>Source review for this profile is in progress.</p>}{person.editorialNote&&<p className="evidence-note">{person.editorialNote}</p>}</section></article></div>
 <section id="related-people" className="related-section"><h2>Connected through shared work</h2><p>Related by {person.tags.join(', ')}. Shared themes do not imply a personal association.</p><div className="related-grid">{related.map(p=><a className="related-card" href={personPath(p.id)} key={p.id}><strong>{p.name}</strong><span>{p.tags.filter(t=>person.tags.includes(t)).join(' · ')}</span></a>)}</div></section></main>}
 const visible=list.filter(p=>(tag==='All'||p.tags.includes(tag))&&[p.name,p.place,p.relevance,...p.tags].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <main id="page-content" className="route-page leadership-page"><nav className="breadcrumbs"><a href="/">Gujarat</a><span>/</span><span>Leadership & personalities</span></nav><header className="directory-heading"><span className="eyebrow">ગુજરાતનું ગૌરવ</span><h1 tabIndex={-1}>People, ideas<br/><em>and enduring contributions.</em></h1><p>Explore public leadership, science, literature and enterprise through the lives and work of people connected with Gujarat.</p></header>
 <div className="directory-controls"><label>Find a personality<input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Name, place or area of work"/></label><label>Area of contribution<select value={tag} onChange={e=>setTag(e.target.value)}><option>All</option>{tags.map(t=><option key={t}>{t}</option>)}</select></label><span role="status">{visible.length} profiles</span></div>
 <div className="personality-grid">{visible.map((p,i)=><article className={`personality-card ${p.id==='narendra-modi'?'featured-person':''}`} key={p.id}><a className="personality-image" href={personPath(p.id)} aria-label={`Read about ${p.name}`}><Portrait person={p}/></a><div className="personality-copy"><span className="eyebrow">{p.id==='narendra-modi'?'PUBLIC LEADERSHIP':p.tags[0]}</span><h2><a href={personPath(p.id)}>{p.name}</a></h2><p className="profile-meta">Born {p.born} · {p.place}</p><p>{p.relevance}</p><div className="tag-list">{p.tags.map(t=><button key={t} onClick={()=>setTag(t)} aria-label={`Filter by ${t}`}>{t}</button>)}</div><a className="text-button" href={personPath(p.id)}>Read full profile ↗</a></div></article>)}</div>{!visible.length&&<p className="empty-state">No matching profiles. Try another name or choose All.</p>}</main>
}
