import {useState} from 'react';
import people from '../data/personalities-data.json';
import { additionalPersonalities } from '../data/additional-personalities.js';
import {personPath} from '../routes.js';
import {portraitFor} from '../data/portraits.js';
import {peopleCatalog} from '../data/people-catalog.js';
import {useLanguage,translateText,LanguageSwitch} from '../locale/context.js';
const labels={biography:'Biography',context:'Historical context',reading:'Reading and reflection',contributions_gujarat:'Gujarat connection',contributions_india:'Contribution to India',contributions_international:'Wider influence',roles:'Roles and responsibilities',vision:'Ideas and vision',lessons:'Legacy and reflection'};
function sourceLabel(source){if(typeof source!=='string')return source.title||source.url;try{return new URL(source).hostname}catch{return source}}
function PortraitSource({person}) {const portrait=portraitFor(person);if(!portrait)return null;let url=portrait.source;if(portrait.original?.includes('wikimedia.org')) {const original=new URL(portrait.original);const name=decodeURIComponent(original.pathname.split('/').pop()).replace(/^\d+px-/,'');url=`https://${original.pathname.includes('/commons/')?'commons.wikimedia.org':'en.wikipedia.org'}/wiki/File:${encodeURIComponent(name)}`;}return <a className="portrait-credit" href={url} target="_blank" rel="noopener noreferrer">{person.name==='Narsinh Mehta'?'Traditional depiction · image source':'Portrait source & attribution'} ↗</a>}
function Portrait({person}){const [failed,setFailed]=useState(false);const portrait=portraitFor(person);const src=portrait?.src || (person.image?.startsWith('assets/')?`/${person.image}`:null);return src&&!failed?<img src={src} alt={person.name==='Narsinh Mehta'?'Traditional depiction of Narsinh Mehta':`Portrait of ${person.name}`} onError={()=>setFailed(true)} loading="lazy"/>:<div className="portrait-placeholder" aria-label={`Portrait unavailable for ${person.name}`}><span>{person.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><small>Portrait unavailable</small></div>}
export default function PersonalitiesPage({id,search=''}){
 const [query,setQuery]=useState('');const {language,setLanguage}=useLanguage();const tag=new URLSearchParams(search).get('tag')||'All';
 const list=[...peopleCatalog].sort((a,b)=>a.id==='narendra-modi'?-1:b.id==='narendra-modi'?1:0);
 const person=list.find(p=>p.id===id);const tags=[...new Set(list.flatMap(p=>p.tags))];
 if(id&&!person)return <main id="page-content" className="route-page"><h1 tabIndex={-1}>Profile not found</h1><a href="/leadership">Browse personalities</a></main>;
 if(person){const related=list.filter(p=>p.id!==id&&p.tags.some(t=>person.tags.includes(t)));return <main id="page-content" className="route-page profile-page">
 <nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Gujarat</a><span>/</span><a href="/leadership">Leadership & personalities</a><span>/</span><span>{person.name}</span></nav>
 <PortraitSource person={person}/>
 <header className="profile-hero"><div className="profile-portrait"><Portrait person={person}/></div><div><span className="eyebrow">PEOPLE WHO SHAPED GUJARAT</span><h1 tabIndex={-1}>{person.name}</h1>{(person.born||person.place)&&<p className="profile-meta">{person.born&&<>Born {person.born}</>}{person.born&&person.place&&" · "}{person.place}</p>}<LanguageSwitch/><p className="profile-intro">{person.relevance}</p><div className="tag-list">{person.tags.map(t=><a key={t} href={'/leadership?tag='+encodeURIComponent(t)}>{t}</a>)}</div></div></header>
 <div className="reading-layout"><aside className="chapter-nav"><h2>In this profile</h2>{Object.keys(person.details).map(k=><a key={k} href={'#'+k}>{labels[k]||k}</a>)}<a href="#related-people">Related people</a><a href="#profile-sources">Sources</a></aside><article className="reading-body">{Object.entries(person.details).map(([k,text])=><section id={k} key={k}><h2>{labels[k]||k}</h2><p>{text}</p></section>)}<section id="profile-sources"><h2>Sources & context</h2>{person.sources?.length?<ul className="source-list">{person.sources.map((s,i)=><li key={i}><a href={typeof s==='string'?s:s.url} target="_blank" rel="noopener noreferrer">{sourceLabel(s)} ↗</a></li>)}</ul>:<p>Source review for this profile is in progress.</p>}{person.editorialNote&&<p className="evidence-note">{person.editorialNote}</p>}</section></article></div>
 <section id="related-people" className="related-section"><h2>Connected through shared work</h2><p>Related by {person.tags.join(', ')}. Shared themes do not imply a personal association.</p><div className="related-grid">{related.map(p=><a className="related-card" href={personPath(p.id)} key={p.id}><strong>{p.name}</strong><span>{p.tags.filter(t=>person.tags.includes(t)).join(' · ')}</span></a>)}</div></section></main>}
 const visible=list.filter(p=>(tag==='All'||p.tags.includes(tag))&&[p.name,p.place,p.relevance,...p.tags,...[p.name,p.relevance,...p.tags].map(t=>translateText(t,language))].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <main id="page-content" className="route-page leadership-page"><nav className="breadcrumbs"><a href="/">Gujarat</a><span>/</span><span>Leadership & personalities</span></nav><LanguageSwitch/><header className="directory-heading"><span className="eyebrow">ગુજરાતનું ગૌરવ</span><h1 tabIndex={-1}>People, ideas<br/><em>and enduring contributions.</em></h1><p>Explore public leadership, science, literature and enterprise through the lives and work of people connected with Gujarat.</p></header>
 <div className="directory-controls"><label>Find a personality<input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Name, place or area of work"/></label><nav className="tag-list" aria-label="Filter by area of contribution"><a href="/leadership" aria-current={tag==='All'?'page':undefined}>All</a>{tags.map(t=><a key={t} href={'/leadership?tag='+encodeURIComponent(t)} aria-current={tag===t?'page':undefined}>{t}</a>)}</nav><span role="status">{visible.length} profiles</span></div>
 <div className="personality-grid">{visible.map((p,i)=><article className={`personality-card ${p.id==='narendra-modi'?'featured-person':''}`} key={p.id}><a className="personality-image" href={personPath(p.id)} aria-label={`Read about ${p.name}`}><Portrait person={p}/></a><div className="personality-copy"><span className="eyebrow">{p.id==='narendra-modi'?'PUBLIC LEADERSHIP':p.tags[0]}</span><h2><a href={personPath(p.id)}>{p.name}</a></h2>{(p.born||p.place)&&<p className="profile-meta">{p.born&&<>Born {p.born}</>}{p.born&&p.place&&" · "}{p.place}</p>}<p>{p.relevance}</p><div className="tag-list">{p.tags.map(t=><a key={t} href={'/leadership?tag='+encodeURIComponent(t)} aria-label={`Filter by ${t}`}>{t}</a>)}</div><a className="text-button" href={personPath(p.id)}>Read full profile ↗</a></div></article>)}</div>{!visible.length&&<p className="empty-state">No matching profiles. Try another name or choose All.</p>}</main>
}
