import { build } from 'esbuild';
import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { resolve, dirname } from 'node:path';
import { createElement } from 'react';
import { renderToString } from 'react-dom/server';
const temp=resolve('.sites-runtime');
await mkdir(temp,{recursive:true});
const appPath=resolve(temp,'prerender-app.mjs');
await build({entryPoints:['src/App.jsx'],outfile:appPath,bundle:true,platform:'node',format:'esm',jsx:'automatic',jsxImportSource:'@localization',alias:{'@localization':resolve('src/locale')},external:['react','react/*','react-dom/*','/assets/*'],loader:{'.css':'empty'},logLevel:'silent'});
const {default:App}=await import(pathToFileURL(appPath));
const load=async name=>JSON.parse(await readFile(`src/data/${name}.json`,'utf8'));
const [people,districts,schemes,atlas,connections,objects,documentary,environment]=await Promise.all(['personalities-data','district-texts','gaurav-schemes-data','historical-atlas','connections','objects','documentary-people','environment'].map(load));
const slug=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const routes=['/','/leadership','/districts','/development','/explore-deeper',...people.map(p=>`/leadership/${p.id}`),...Object.keys(districts).map(s=>`/districts/${s}`),...schemes.flatMap((s,i)=>[`/development/${slug(s.name)}`,`/development/${i}`])];
routes.push(...JSON.parse(await readFile('scripts/current-routes.json','utf8')));
for(const [kind,records] of Object.entries({history:atlas.sites,connections,objects,people:documentary,environment:environment.regions})) routes.push(`/explore/${kind}`,...records.map(r=>`/explore/${kind}/${r.id}`));
const html=await readFile('dist/index.html','utf8');
if(!html.includes('<div id="root"></div>')) throw Error('Expected fresh Vite output before prerendering.');
const escape=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const route of [...new Set(routes)]){
  const markup=renderToString(createElement(App,{initialPath:route}));
  const headings=[...markup.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/g)];
  const title=route==='/'?'Gujarat Unveiled':headings.at(-1)?.[1].replace(/<[^>]*>/g,' ')+' · Gujarat Unveiled';
  const page=html.replace('<div id="root"></div>',`<div id="root" data-prerender-path="${escape(route)}">${markup}</div>`).replace(/<title>.*?<\/title>/,`<title>${title}</title>`);
  const output=resolve('dist',`.${route}`, 'index.html');
  await mkdir(dirname(output),{recursive:true}); await writeFile(output,page);
}
await writeFile('dist/prerender-routes.json',JSON.stringify([...new Set(routes)],null,2)+'\n');
await rm(appPath,{force:true});
console.log(`Prerendered ${new Set(routes).size} routes with matching hydration markers.`);
